version: '3.3'

services:
  postgres:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      endpoint_mode: dnsrr
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users

  authserver:
    image: localhost:5000/authserver
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      COOKIE_DOMAIN: "127.0.0.1"
      DB_URI: "postgresql+psycopg2://postgres:secret@postgres/users"
    volumes:
      - "/Users/tdavis/projects/magicauthserver-advanced:/testing"
    ports:
      - 5050:80

services:
  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      endpoint_mode: dnsrr