version: '3.3'
# This is an example configuration for a Docker Swarm
services:
  postgres:
    image: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      endpoint_mode: dnsrr
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: users

  authserver:
    image: localhost:5000/authserver
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      COOKIE_DOMAIN: "example.com"
      DB_URI: "postgresql+psycopg2://postgres:secret@postgres/users"
    volumes:
      - "<HOST_PATH>:/testing"
    ports:
      - 5050:80

  revproxy:
    image: localhost:5000/revproxy
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - "<HOST_PATH>/servers.ini:/etc/servers.ini:ro"
      - "<SECURE_HOST_PATH>/certs:/etc/letsencrypt"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 80:80
      - 443:443

  redis:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      endpoint_mode: dnsrr
    volumes:
      - "<HOST_PATH>:/data"